### ISSUE TITLE
HKDF_expand_label reads entire buffer

### ISSUE THREAD

**Issue by lukasvrenner** [lukasvrenner/turtls#10]
The function has a buffer to store the label, but when it calls hkdf::expand, it passes the entire buffer rather than just the label.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the hkdf_expand_label function to pass only the used portion of the hkdf_label buffer to hkdf::expand, addressing the issue where the entire buffer was being passed instead of just the label data.

You can review changes in this commit: https://github.com/lkilu6456546/lukasvrenner-turtls-10/commit/475b959da53bf016f7f7d9bc75d5b864862dbf48.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
